---
- name: Sync secrets from Infisical to Kubernetes
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    infisical_cli_path: "/usr/local/bin/infisical"
    infisical_api_url: "http://infisical.infisical.svc.cluster.local:8080/api"
    environments:
      - dev
      - staging
      - production
  tasks:
    - name: "Sync database credentials for each service"
      shell: |
        {{ infisical_cli_path }} secrets get DATABASE_URL \
          --environment={{ item[1] }} \
          --api-url={{ infisical_api_url }} \
          --token=$(kubectl get secret {{ item[0] }}-infisical-token -n {{ item[0] }} -o jsonpath='{.data.token}' | base64 -d)
      register: db_urls
      loop: "{{ ['user-service', 'billing-service', 'auth-service'] | product(environments) | list }}"
      ignore_errors: true

    - name: "Create database secret for each service"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ item.item[0] }}-db"
            namespace: "{{ item.item[0] }}"
          type: Opaque
          stringData:
            url: "{{ item.stdout | default('') }}"
      loop: "{{ db_urls.results }}"
      when: item.rc == 0