apiVersion: v1
kind: Secret
metadata:
  name: jcr-registry-secret
  namespace: flux-system
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "jcr.example.com": {
          "username": "admin",
          "password": "changeme",
          "auth": "YWRtaW46Y2hhbmdlbWU="
        }
      }
    }
---
# Create the same secret in all namespaces that need to pull images
apiVersion: v1
kind: Secret
metadata:
  name: jcr-registry-secret
  namespace: user-service
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "jcr.example.com": {
          "username": "admin",
          "password": "changeme",
          "auth": "YWRtaW46Y2hhbmdlbWU="
        }
      }
    }
---
# ServiceAccount patch to use the registry secret
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: user-service
imagePullSecrets:
- name: jcr-registry-secret