apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: user-service

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - network-policy.yaml

configMapGenerator:
  - name: user-service-config
    files:
      - config.properties

commonLabels:
  app.kubernetes.io/name: user-service
  app.kubernetes.io/part-of: base-application
  app.kubernetes.io/managed-by: flux