# Kong Ingress configuration for services
# This creates Kong Ingress resources that route traffic to backend services
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: default-kong-ingress
  namespace: kong
route:
  strip_path: true
  preserve_host: true
  regex_priority: 0
upstream:
  healthchecks:
    active:
      healthy:
        interval: 10
        successes: 2
      unhealthy:
        interval: 5
        http_failures: 5
        tcp_failures: 5
    passive:
      healthy:
        successes: 5
      unhealthy:
        http_failures: 5
        tcp_failures: 5
---
# User Service Route
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-service
  namespace: user-service
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/strip-path: "true"
    konghq.com/preserve-host: "true"
    konghq.com/plugins: rate-limiting,cors
spec:
  rules:
  - http:
      paths:
      - path: /api/v1/users
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 80
---
# Global Rate Limiting Plugin
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limiting
  namespace: kong
config:
  minute: 100
  hour: 10000
  policy: local
plugin: rate-limiting
---
# CORS Plugin
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors
  namespace: kong
config:
  origins:
  - "*"
  methods:
  - GET
  - POST
  - PUT
  - DELETE
  - PATCH
  - OPTIONS
  headers:
  - Accept
  - Accept-Version
  - Content-Length
  - Content-MD5
  - Content-Type
  - Date
  - X-Auth-Token
  - Authorization
  exposed_headers:
  - X-Auth-Token
  credentials: true
  max_age: 3600
plugin: cors
---
# Request Transformer Plugin for adding headers
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-transformer
  namespace: kong
config:
  add:
    headers:
    - "X-Forwarded-Prefix:/api/v1"
    - "X-Kong-Proxy:true"
plugin: request-transformer
---
# JWT Authentication Plugin (disabled by default)
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: jwt-auth
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
config:
  key_claim_name: kid
  claims_to_verify:
  - exp
plugin: jwt
---
# Prometheus Metrics Plugin
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: prometheus
  namespace: kong
  labels:
    global: "true"
config:
  status_code_metrics: true
  latency_metrics: true
  bandwidth_metrics: true
  upstream_health_metrics: true
plugin: prometheus