apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: infisical
  namespace: flux-system
spec:
  interval: 1h
  url: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: infisical
  namespace: infisical
spec:
  interval: 30m
  chart:
    spec:
      chart: infisical-standalone
      version: "0.4.0"
      sourceRef:
        kind: HelmRepository
        name: infisical
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Platform cluster configuration
    nodeSelector:
      cluster-type: platform
    priorityClassName: platform-critical
    
    infisical:
      # Admin credentials configuration
      admin:
        initialCredentials:
          autoGenerate: true
          secretName: "infisical-initial-creds"
      
      # Resource configuration
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "2"
          memory: "2Gi"
      
      # Persistence
      persistence:
        enabled: true
        size: 50Gi
        storageClass: vultr-block-storage
    
    # PostgreSQL configuration
    postgresql:
      enabled: true
      auth:
        postgresPassword: infisical123
        database: infisical
      primary:
        nodeSelector:
          cluster-type: platform
        persistence:
          enabled: true
          size: 20Gi
          storageClass: vultr-block-storage
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
    
    # Redis configuration
    redis:
      enabled: true
      master:
        nodeSelector:
          cluster-type: platform
        persistence:
          enabled: true
          size: 10Gi
          storageClass: vultr-block-storage
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
    
    # Service configuration
    service:
      type: ClusterIP
      port: 8080
    
    # Ingress can be enabled if needed
    ingress:
      enabled: false
      
  # Post-install hook to run configuration
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: infisical
            patch: |
              - op: add
                path: /spec/template/spec/initContainers
                value:
                  - name: wait-for-db
                    image: busybox:1.36
                    command: ['sh', '-c', 'until nc -z infisical-postgresql 5432; do echo waiting for db; sleep 2; done']