apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: user-service-infrastructure
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/nestharus/base-application.git
  ref:
    branch: main
  ignore: |
    /*
    !/services/user-service/src/main/resources/infrastructure/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: user-service-infrastructure
  namespace: flux-system
spec:
  interval: 5m
  path: "./services/user-service/src/main/resources/infrastructure"
  prune: true
  sourceRef:
    kind: GitRepository
    name: user-service-infrastructure
  targetNamespace: user-service
  validation: client
  postBuild:
    substitute:
      cluster_name: "base-k8s-cluster"
      region: "ewr"
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: infrastructure
    - name: crossplane-system